### ISSUE TITLE
I used bootstrap-buildout.py instead of bin/pip. Would it be the case to update README?

### ISSUE THREAD

**Issue by idgserpro** [collective/minimalplone4#1]
Instead of using bin/pip to install buildout to your virtualenv, you can use bootstrap from https://bootstrap.pypa.io/bootstrap-buildout.py, run `python bootstrap-buildout.py` and then `bin/buildout`. The nice thing about this approach is that is consistent with a lot of packages that have a bootstrap.py in it's repository. Do you think this would be a nice addition to the docs?

**Comment by idgserpro** [comment]
Relevant: https://github.com/buildout/buildout/issues/289

**Comment by frisi** [comment]
running `python bootstrap-buildout.py` without any parameters can lead to the problem (google for "buildout loop") that people try to prevent in https://github.com/buildout/buildout/issues/289

when using buildouts with multiple colleagues we learned that it's less error prone to document `pip install -r requirements.txt` in the buildout's README.txt and update requirements.txt and versions.cfg if other versions of zc.buildout and/or setuptools are needed than to require all users to follow these instructions in the README `vpython/bin/python2.7 bootstrap-buildout.py --buildout-version 2.3.1 --setuptools-version=12.4` 

personally i use `pip install` for new  projects and update old buildouts as i need to work with them.

if this is the general tenor in the plone community (see [buildout.coredev documentation](https://buildoutcoredev.readthedocs.org/en/latest/intro.html#setting-up-your-development-environment) we should not replace `pip install` with `bootstrap-buildout.py` but do exactly the opposite (and document that properly).

**Comment by idgserpro** [comment]
I'm closing this issue because of https://github.com/plone/Products.CMFPlone/issues/2001.
